# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: true

r_binary_packages:
  - rjags

r_packages:
  - covr

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

after_success:
- Rscript -e 'library(covr); codecov()'
