# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: true
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter
  - sudo apt-get update
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

r_packages:
  - covr

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

after_success:
- Rscript -e 'library(covr); codecov()'
